### ISSUE TITLE
moban version 6 api update

### ISSUE THREAD

**Issue by chfw** [moremoban/moban-velocity#2]
reference: https://github.com/moremoban/moban/pull/302

No longer, the first parameter is a list of directories but an instance of `fs.multifs.MultFS`.

as the following:

```
class Engine(object):
    def __init__(self, template_fs, options=None):
```

**Comment by chfw** [comment]
@ayan-b , would you like to bring it to moban 0.6.x+?

**Comment by ayan-b** [comment]
@chfw Sure. I will try to take a look this weekend.

**Comment by chfw** [comment]
That's quick response!
